services:
  orpheusdl-web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./config:/app/config:rw # OrpheusDL Config Location
      - ./extensions:/app/extensions:rw # Extensions Location
      - ./modules:/app/modules:rw # Modules Location
      - ./logs:/app/logs # Logging File Location
      - ./downloads:/app/downloads # Downloaded Files Location
    environment:
      - FLASK_APP=web.run
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - GUNICORN_CMD_ARGS="--log-level info"
      - WEB_SECRET=orpheusdl-web-secret-key-2025
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"